'''
    conversiones_generales, es una tabla de traducción usada para convertir
    las cosas que escribes, a cosas que la computadora retorna de
    forma escrita, ejemplo: "Yo soy" -> "Tu eres"
'''

conversiones_generales = {
    "soy": "eres",
    "estaba": "estabas",
    "yo": "tu",
    "yo queria": "tu querias",
    "yo tengo": "tu tienes",
    "yo quisiera": "tu quisieras",
    "mi": "tu",
    "mis": "tus",
    "eres": "soy",
    "tu tienes": "yo tengo",
    "tu quisieras": "yo tengo",
    "tu": "mi",
    "tus": "mis",
    "tu": "yo",
    "my" : "your",
    "me" : "te",
    "te" : "me",
    "siento" : "sientes",
    "sientes" : "siento",
    "creo" : "crees",
    "crees" : "creo",
    "veo" : "ves",
    "ves" : "veo",
    "estoy" : "estas",
    "estas" : "estoy",
    "encuentro" : "encuentras",
}

general_conversions ={
    "am"   : "are",
    "was"  : "were",
    "i"    : "you",
    "i'd"  : "you would",
    "i've"  : "you have",
    "i'll"  : "you will",
    "my"  : "your",
    "are"  : "am",
    "you've": "I have",
    "you'll": "I will",
    "your"  : "my",
    "yours"  : "mine",
    "you"  : "me",
    "me"  : "you"
}


'''
    Verbos y palabras consideradas para realizar la traducción
'''
translate_converions = {  
    "one" : "uno",
    "uno" : "one",
    "two" : "dos",
    "dos" : "two",
    "three" : "tres",
    "tres" : "three",
    "four" : "cuatro",
    "cuatro" : "four",
    "five" : "cinco",
    "cinco" : "five",
    "six" : "seis",
    "seis" : "six",
    "seven" : "siete",
    "siete" : "seven",
    "eight" : "ocho",
    "ocho" : "eight",
    "nine" : "nueve",
    "nueve" : "nine",
    "i" : "yo",
    "yo" : "i",
    "he" : "el",
    "el" : "he",
    "she" : "ella",
    "ella" : "she",
    "it" : "eso",
    "eso" : "it",
    "you" : "tu",
    "tu" : "you",
    "we" : "nosotros",
    "nosotros" : "we",
    "they" : "ellos",
    "ellos" : "they",
    "am" : "soy",
    "soy" : "am",
    "is" : "es",
    "es" : "is",
    "are" : "son",
    "son" : "are",
    "i'm" : "yo soy",
    "me" : "yo",
    ########################
    "who" : "quién",
    "quién" : "who",
    "what" : "qué",
    "que" : "what",
    ##########Verbos##############
    "answer" : "contestar",
    "contestar" : "answer",
    "call" : "llamar",
    "llamar" : "call",
    "can" : "poder",
    "poder" : "can",
    "do" : "hacer",
    "hacer" : "do",
    "come" : "venir",
    "venir" : "come",
    "feel" : "sentir",
    "sentir" : "feel",
    "get" : "obtener",
    "obtener" : "get",
    "give" : "dar",
    "dar" : "give",
    "go" : "ir",
    "ir" : "go",
    "happen" : "suceder",
    "suceder" : "happen",
    "have" : "tener",
    "tener" : "have",
    "hear" : "oir",
    "oir" : "hear",
    "help" : "ayudar",
    "ayudar" : "help",
    "know" : "saber",
    "saber" : "know",
    "laugh" :"reir",
    "reir" : "laugh",
    "leave" : "abandonar",
    "abandonar" : "leave",
    "let" : "dejar",
    "dejar" : "let",
    "like" : "gustar",
    "gustar" : "like",
    "live" : "vivir",
    "vivr" : "live",
    "look" : "ver",
    "ver" : "look",
    "love" : "amar",
    "amar" : "love",
    "make" : "hacer",
    "hacer" : "make",
    "means" : "significar",
    "significar" : "means",
    "mind" : "importar",
    "importar" : "mind",
    "move" : "mover",
    "mover" : "move",
    "need" :  "necesitar",
    "necesitar" : "need",
    "open" : "abrir",
    "abrir" : "open",
    "pull" : "jalar",
    "jalar" : "pull",
    "push" : "empujar",
    "empujar" : "push",
    "reply" : "responder",
    "responder" : "reply",
    "say" : "decir",
    "decir" : "say",
    "see" : "mirar",
    "mirar" : "see",
    "seem" : "parecer",
    "parecer" : "seem",
    "sit" : "sentar",
    "sentar" : "sit",
    "smile" : "sonreir",
    "sonreir" : "smile",
    "start" : "empezar",
    "empezar" : "starts",
    "stop" : "terminar",
    "terminar" : "stop",
    "take" : "tomar",
    "tomar" : "take",
    "talk" : "hablar",
    "hablar" : "talk",
    "tell" : "decir",
    "decir" : "tell",
    "think" : "pensar",
    "pensar" : "think",
    "try" : "probar",
    "probar" : "try",
    "use" : "usar",
    "usar" : "use",
    "wait" : "esperar",
    "esperar" : "wait",
    "walk" : "caminar",
    "caminar" : "walk",
    "want" : "querer",
    "querer" : "want",
    "work" : "trabajar",
    "trabajar" : "work",
    "play" : "jugar",
    "jugar" : "play",
    "caminar" : "walk",
    "walk" : "caminar",
    "drive" : "manejar",
    "manejar" : "drive",
    "run" : "correr",
    "correr" : "run",
    "drink" : "beber",
    "beber" : "drink",
}